name: tftp
description: A lib for Trivial File Transfer Protocol(TFtp) server and client.
version: 1.1.0
author: FourLeaf <gundamwing.wei@gmail.com>
homepage: https://github.com/FourLeafTec/tftp

environment:
  sdk: ">=2.17.5 <3.0.0"

# dependencies:

